### ISSUE TITLE
Plugins approved by Sylius

### ISSUE THREAD

**Issue by Zales0123** [mangoweb-sylius/SyliusExtendedChannelsPlugin#1]
Hello!

I'm Mateusz, I work in Sylius company and one of my roles is Plugin Curator - I'm responsible for checking out Sylius Plugins that appear in our ecosystem. We would really love to display this one (and other your plugins, like [SyliusJezekDuelPlugin](https://github.com/mangoweb-sylius/SyliusPaymentFeePlugin), [SyliusPaymentFeePlugin](https://github.com/mangoweb-sylius/SyliusJezekDuelPlugin) and [SyliusMailChimpPlugin](https://github.com/mangoweb-sylius/SyliusMailChimpPlugin)) on our officially accepted plugins list (https://sylius.com/plugins/), as I strongly believe they could be useful for other people in the community. What's more, you're our Partner, so it's obvious we want to promote your work :)
The only problem is, we have some strict requirements for the plugin that is meant to be displayed on our website. One of the most important are properly developed tests. Sadly, your plugins have neither unit (PHPSpec/PHPUnit) nor acceptance (Behat) tests. Do you think you would be able to provide them? It would be great if we could extend our accepted plugins set with some of yours repositories :)

If you have any question, please, feel free to ask me.

Nevertheless, thank you for choosing Sylius and for your great job!

**Comment by hornofj** [comment]
@Zales0123 Hi Mateusz, it took some time to allocate resources to do this but we are happy to announce that the features of this plugin are covered with Behat tests now. Other plugins will follow shortly. Could you have a look and let us know if there is something other blocking accepting the plugin? Thanks!

**Comment by Zales0123** [comment]
Hello @Zales0123, I'm sorry for such a long response time. Thank you for creating some tests, it's a great thing you've given it a try :) Some few comments to your test suite:

1. Remember that scenarios should be as business-oriented and non-technical as possible. Therefore you should avoid sentences as `I run command to cancellation orders` and use instead `I cancel orders` - scenario files should be easy to read (and write) for somebody who is totally not a programmer :)

2. The structure of Behat scenario should always follow `Given` -> `When` -> `Then` pattern. You can skip `Given` (it's usually handled by the background which is in fact a one, big `Given` block 🐎), but there always must be some action (`When`) and assertion (`Then`)

3. The structure of the feature file description is also important, it should clearly describe the purpose of an implemented functionality and should follow the pattern:

```
In order to ... // Why?
As a ... // Who? (beneficient of the feature)
I want to be able to ... // What?
```

4. Try to keep the features as small as possible, but still with sufficient amount of steps to describe the feature 🚀 [This feature](https://github.com/mangoweb-sylius/SyliusExtendedChannelsPlugin/blob/master/features/cancel_unpaid_orders_for_certain_payment_method.feature) is enormous, for example, especially background... maybe steps `the guest customer placed an order with the number...` could be moved to specific scenarios?

5. It would be great if you configure some CI server and run your tests on it. You would be then sure that they're working properly and somebody checking them (me, for example 😄) would not have to install a plugin to run them.

And regarding the installation - I had some problems with installing a development version of this plugin:

<img width="956" alt="Zrzut ekranu 2019-06-25 o 13 26 31" src="https://user-images.githubusercontent.com/6212718/60095410-c6333a00-974e-11e9-8d12-bfceb903ab28.png">

It would be great if you check it out, as I'll be able to help you more if I manage to run it on my local machine :)

Sorry one more time for the response delay, good job anyway! 🏅

**Comment by hornofj** [comment]
@Zales0123 we fixed and changed all according your comments and added CI so you can see the build passing. anything else? thanks!

**Comment by Zales0123** [comment]
Hello Johan, one more time, sorry for the response time. Some really tiny comments yet:

- When following the installation instruction the plugin is not installed fully. You should also mention, that `sylius_order.order_expiration_period` and `sylius_order.expiration_method_codes` needs to be configured and database schema should be updated (with migrations preferably)
- Some at least basic unit tests (with PHPSpec, PHPUnit or anything else :)) should be added

But generally, the fixes and plugin itself are good, we would be happy to list it as an officially approved Sylius plugin 🎉 I'll let you know when we post it to the website and provide you an "Approved by Sylius" badge. Thanks for the cooperation! 🥇
